docs/index.rst, docs/romanisim/refs.rst, romanisim/catalog.py, romanisim/image.py, romanisim/l1.py, romanisim/ramp.py, romanisim/util.py
This PR adds support for flat fields and gains.
CRDS currently supplies flat fields only for F158, so a flat field of 1 (i.e., no-op) is used when a flat field cannot be found.
The implementation is slightly interesting because of the goal of continuing to support galsim's "photon shooting" mode.  The simulation has an initial phase where it figures out how many photons should enter each pixel over the whole exposure time, and then plays games figuring out how many of those photons enter each read & resultant, and how those eventually get translated into slopes.
For if all flat values were less than one, it would be straightforward to take the simulated image and sample it via the binomial distribution down to the "effective" time of each pixel---ignoring any chromaticity of the flat …
=> Add support for flat field and gain reference files.

.flake8, docs/romanisim/l1.rst, docs/romanisim/l2.rst, pyproject.toml, romanisim/image.py, romanisim/l1.py, romanisim/nonlinearity.py, romanisim/wcs.py
This adds a new module that handles classical non-linearity.
There's some complexity needed to handle both images that already include poisson noise (e.g., from galsim's photon shooting rendering approach) and non-linearity.  That took a while to get right but ends up not being very expensive.  There is documentation in the l1 documentation and modules.
Also fix a bug in the updated exception logic in GWCS._xy that was preventing any images from being made when using CRDS.
=> Implement classical non-linearity

README.md
The code coverage badge had a dangling reference to master; this has been replaced with main.
=> Fix codecov badge (master -> main).

.github/workflows/ci.yml, romanisim/image.py
The dark rate is supposed to be in electrons / s, but it was formerly in DN / s.  Multiplying by the gain addresses this issue.
=> Fix units of dark rate.

.github/workflows/ci.yml, romanisim/l1.py, romanisim/tests/test_l1.py
This PR adds unit tests for the L1 module.  This module is pretty well self-contained and testing works out without any surprises.  There were a couple of minor improvements as well, allowing the L1 module to simulate images that aren't 4k x 4k (to speed tests), and to optionally not use gain measurements.  A few unused vestigial arguments were also removed.
I could not think of especially good tests of correctness.  Even reasonable things like "ramps increase" or "ramps don't measure more photons in total than were accumulated in the whole exposure" aren't true because of read noise.  I turn off read noise and do some basic tests, and then turn it back on and just do sanity tests (... is the shape right?), as well as testing that the read noise applied looks like what one would expect. …
=> Add unit tests for L1 module

docs/romanisim/bandpass.rst, romanisim/image.py, romanisim/psf.py, romanisim/tests/test_image.py
This adds tests demonstrating PSF rendering, analytic model galaxy rendering, and L2 image creation.
This decorates an existing test that made an image in L2 format, and additionally makes some new image rendering tests, intending to demonstrate that we successfully put PSFs and galaxies in images.  I have tried to make these tests non-trivial by avoiding using galsim to do the rendering, and instead doing my own dumb brute force rendering techniques---basically just rendering the images in a hugely oversampled way and then binning down.  I then verify that the inner few arcseconds of the resulting images agree at the 5 sigma level, including only Poisson errors, for sources with 100k total counts. Agreement is quite good, though there are small differences everywhere due to the imperfect …
=> Add SOC tests for DMS 214, 215, 216 (image rendering)

romanisim/catalog.py, romanisim/image.py, romanisim/l1.py, romanisim/parameters.py, romanisim/tests/test_image.py, romanisim/tests/test_l1.py, romanisim/tests/test_wcs.py, romanisim/wcs.py, scripts/romanisim-make-image
- Add function trimming input catalogs to sources vaguely near the detector
- Allow sending either list[CatalogObject] or Table to simulate_counts / simulate_counts_generic
- Make code more efficient when sending large number of sources, most of which fall off the detector.
- Refactor IPC code to improve testing.
- Make default ra/dec specification specify the location of the center of the WFI array rather than the boresight.
- Update WCS tests & documentation accordingly.
- Add SOC tests for requirements:
- DMS220: Adding read noise.
- DMS225: inject a source into a ramp.
- DMS226: Convolving an image with an IPC kernel.
- DMS227: Making an L1 output file with the right structure.
=> Changes supporting adding tests for uncalibrated image simulation

docs/conf.py
`tomli` is implemented read-only as `tomllib` in Python 3.11
=> `tomli` is implemented read-only as `tomllib` in Python 3.11

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, pyproject.toml, tox.ini
This PR abstracts CI workflows to the OpenAstronomy workflows; this should reduce maintenance for updating and maintaining actions. Additionally, these changes move the majority of MacOS jobs to the weekly scheduled workflow. This should alleviate the issue where the limited MacOS runners for the organization are not available for CI jobs.
=> use OpenAstronomy workflows and move MacOS jobs to weekly schedule

pyproject.toml, requirements-dev.txt, romanisim/image.py, romanisim/tests/test_cr.py, romanisim/wcs.py
This removes the simulator's dependency on romancal, which should not be needed and is causing test failures.
=> Remove romancal dependency.

.readthedocs.yaml, docs/rtd_environment.yaml
attempts to fix RTD build by using the new `build` block (`python.version` is deprecated) and also building the environment with `mamba` to avoid issues with availability of `openssl` and `graphviz`
=> fix readthedocs configuration

.github/workflows/ci_cron.yml, requirements-dev.txt
Resolves [SCSB-69](https://jira.stsci.edu/browse/SCSB-69)
run `devdeps` tests against both `astropy` and `numpy` pre-built `pre` wheels
=> test against pre-built binaries of `numpy`

docs/romanisim/install.rst, docs/romanisim/l2.rst, docs/romanisim/overview.rst, docs/romanisim/util.rst, romanisim/image.py, romanisim/l1.py, romanisim/parameters.py, romanisim/ramp.py, romanisim/ramp_fit_casertano.pyx, romanisim/tests/test_image.py, romanisim/tests/test_l1.py
* Propagate DQ information from image simulation to ramp fitting so that we can properly treat saturated sources and cosmic rays when fitting ramps.
* Update docs.
* Add pedestal to L1 image so that noise doesn't lead to clipping at zero.
* Update tests to accommodate new L1 pedestal---don't assume that there is no pedestal.
* Update cython ramp fitting to mark more things as C variables; ~100x speedup (oops).
=> Propagate DQ information from image simulation to ramp fitting.

romanisim/ramp.py, romanisim/tests/test_l1.py
Update the tests to only print about passing each test once.  Also fix a bug where the case where the read noise is exactly zero triggers bad behavior in ramp fitting.
=> Update tests to be less noisy

romanisim/__init__.py, romanisim/bandpass.py, romanisim/catalog.py, romanisim/image.py, romanisim/l1.py, romanisim/persistence.py, romanisim/tests/test_image.py, romanisim/tests/test_l1.py, romanisim/tests/test_wcs.py, romanisim/wcs.py, scripts/romanisim-make-image
* Move romanisim dq & persistence structures outside of the 'roman' asdf keyword, since romancal assumes it will understand everything under that keyword.
* Add the WCS to romanisim L2 output.
* Remove custom logging formatting to avoid stpipe interaction issue.
* Move crds module imports out of module level.
=> Improve content of romanisim output files

romanisim/__init__.py, romanisim/catalog.py, scripts/romanisim-make-image
This PR swaps a few cases where random number generators were being used without seeds to use input seeds instead.It also continues to play around a bit with the logging.
=> Use seeds more consistently in random number generation.

romanisim/ramp.py, romanisim/ramp_fit_casertano.pyx, romanisim/util.py
This PR refactors the ramp fitting code to use less memory.  The underlying calculations are identical and the same results are obtained as before.  But the new version loops over the array pixel by pixel, doing the complete calculation for each pixel before moving onto the next, while the old version computed intermediate quantities for each pixel before combining them to get the complete results for the array.
The new version is slightly slower; doing a million pixels with 6 resultants takes something like 400 ms with this PR instead of 300 ms it the original version.  I suspect this is because of the less efficient memory access pattern.  Because the arrays are sequential spatially rather than temporally the new pattern which loops over each pixel is not very friendly for caching and …
=> Refactor ramp fitting code to use less memory.

romanisim/__init__.py, romanisim/catalog.py, romanisim/l1.py, romanisim/persistence.py, romanisim/ramp_fit_casertano.pyx, romanisim/wcs.py, scripts/romanisim-make-image
Fix some cosmetic issues and upcoming deprecations.
* types to f4 rather than f8 in catalogs where appropriate
* np.product -> np.prod
* raise an error if you try to get a persistence flux from times _before_ the persistence event occurred
* metadata['exposure']['start_time'] needs to be an astropy Time object.
=> Misc deprecation fixes and test failures.

romanisim/l1.py, romanisim/ris_make_utils.py, romanisim/tests/test_catalog.py, romanisim/tests/test_image.py, romanisim/tests/test_l1.py, romanisim/tests/test_ris_make_utils.py, scripts/romanisim-make-image, scripts/romanisim-make-stack
* DMS217: Parametric source distributions.
* DMS218: Distortion & WCS.
* DMS229: Ramp from counts.
* DMS230: Poisson noise.
A few unrelated changes:
- initialize noise array with zeros instead of empty because galsim wants to cast it before filling it, and can try to cast invalid numbers and emit a warning.
- fix the units on some test_simulate(...) tests to avoid generating sources with 10^20 photons.
=> Add or improve tests for various simulator requirements.

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, JenkinsfileRT_dev, docs/romanisim/install.rst, pyproject.toml, tox.ini
This updates the webbpsf data files used in CI to the latest versions.
=> Update for webbpsf 1.2.1.

JenkinsfileRT_dev
The default Jenkins configuration is causing problems when hitting the CRDS cache, leading to job failures.  This disables the multithreading for the moment.
=> Update jenkins configuration to run single threaded

.github/workflows/ci_cron.yml
the `if: ` block in the weekly CI is checking for the `romancal` repository instead of `romanisim`
=> fix weekly CI trigger

romanisim/image.py, romanisim/parameters.py, romanisim/ris_make_utils.py, romanisim/wcs.py
Added the ability to provide reference file names instead of calling CRDS for matched reference files via the parameters file. Also allows for overriding with flat values, if not using reference files.
=> RCAL-645 Override Reference Files

pyproject.toml, requirements-dev.txt, romanisim/tests/test_catalog.py, romanisim/tests/test_image.py, romanisim/tests/test_l1.py
Added SOC Test decorators for metrics logging via https://github.com/spacetelescope/metrics_logger
=> RCAL-628 SOC Test decorators

romanisim/gaia.py, romanisim/tests/test_gaia.py
I had previously thought that parallax defined the _diameter_ of the circle stars describe as the earth moves.  In fact it's the radius.  This means that we need to remove a factor of two and a comment.
=> Fix parallax definition convention.

romanisim/image.py, romanisim/nonlinearity.py, romanisim/parameters.py, romanisim/tests/test_l1.py, romanisim/tests/test_linear.py
This PR allows ramp fitting to proceed on pixels marked as having problematic linearity.
Formerly we had only two DQ bits---saturation and CR.  Ramp fitting ignored any pixel with a DQ bit so that we didn't include these in the ramps.  When we added the nonlinearity DQ bit, this made us stop fitting ramps on all of the pixels with problematic linearity determination, which is not what we want.
This adds a new parameters.dq_do_not_use set of flags that identifies the flags that should be used for determining which resultants to ignore in ramp fitting.
I also changed the name of the dq bit we're using from nonlinear to no_lin_corr, since I think the latter is a better match to what's happening in the simulator at the moment.
=> Allow ramp fitting to use pixels marked with bad non-linearity.

docs/romanisim/install.rst, romanisim/psf.py, romanisim/ris_make_utils.py, romanisim/tests/test_psf.py
We now use the wcs argument of romanisim.psf.make_psf to attach a WCS to the PSF to ensure that the orientation of the PSF used in the simulation is correct.
=> Ensure correct PSF orientation

romanisim/tests/test_image.py
When the source injection test image was shrunk to 100x100 pixels, the previous tests weren't valid, as the PSF has a radius of 90 pixels. This ticket re-implements the spirit of the tests, as well as fixing a bug.
=> Hotfix to Correct Source Injection Tests

romanisim/wcs.py, scripts/romanisim-make-image, scripts/romanisim-make-stack
After some testing and discussion, it has become clear(er) that the user-provided ```--roll``` argument is really the position angle measured at the aperture's V2Ref/V3Ref (measured from North to YIdl). The handling of this value in ```wcs.py``` was also fixed for the case where the aperture used is BORESIGHT. 
Note that the code in ```wcs.py``` converts this value to ```roll_ref```, which is defined as the angle from North to V3 (towards East) measured at the aperture V2Ref/V3Ref, but from a user perspective, it makes more sense to specify the position angle of the aperture on the sky, hence the clarification provided here.
=> Minor fix to clarify user-provided position angle instead of roll

romanisim/parameters.py, romanisim/ris_make_utils.py, scripts/romancal_make_regtest_l1s.sh, scripts/romanisim-make-image
This PR adds a few new features useful for making regression test files for romancal.
* It adds the read patterns for some new MA tables used in the regression tests.
* It adds a 'pretend-spectral' CLI option to write in the metadata that the image is dispersed even when it's not.
* It adds a new argument to remove the extra romanisim "truth" DQ image, which can otherwise take up most of the data volume of the file.
* It adds a script to generate a minimal set of L1 files that are needed for the regression tests.
* It fills out the v3parity and v3yangle keywords to constant values of -1 and -60.  Confusingly, the exposure level pipeline does not need these keywords to make WCSes, but the mosaic pipeline does.  It's not obvious to me that that makes sense (i.e., maybe we should be doing …
=> Regtest maker functions

romanisim/ris_make_utils.py, romanisim/util.py, romanisim/wcs.py
This adds some values to the target metadata stanza.  romanisim usually just gets an ra/dec as input, so the only values we can meaningfully fill out are those ra/dec.  But there are vaguely reasonable values to which one can set many of the other values as well.
=> Fill out target metadata stanza

docs/romanisim/l2.rst, docs/romanisim/parameters.rst, docs/romanisim/psf.rst, pyproject.toml, romanisim/image.py, romanisim/psf.py, romanisim/tests/test_image.py
This changes the L2 units to be DN/s instead of e/s by dividing by the gain.  This is to support the corresponding changes to rad.
=> Change L2 units to DN/s reflecting changes to L2 schema in rad.

romanisim/image.py, romanisim/psf.py, romanisim/tests/test_image.py, romanisim/tests/test_psf.py
This test lets one pass more arguments to the PSF generation routines, aiming to speed up the tests where we don't care about a lot of accuracy in the PSF but do want to flow things through the whole system.
=> Use nlamba=1 for PSF generation in test to be a bit faster.

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, pyproject.toml
resolves [SCSB-145](https://jira.stsci.edu/browse/SCSB-145)
propagate Astropy's deprecation of Python 3.9 to downstream packages
> [!NOTE]
> this PR was generated automatically by ``batchpr`` :robot:
=> [SCSB-145] require Python 3.10

romanisim/wcs.py
There is an issue with the distortion reference files in CRDS such that wcs.world_to_pixel(wcs.pixel_to_world(...)) only inverts at the 0.05 pix level.  That makes it impossible to do astrometry better than ~0.05 pix.  This replaces wcs.world_to_pixel with wcs.numerical_inverse to avoid this issue.  This is slightly slower, so we will restore the original approach when the reference file issue is resolved.
=> Use numerical inverse to improve WCS accuracy

romanisim/image.py
When make_l2 was converted to report units in DN/s rather than electron/s, a bug was introduced where the variances were divided by the gain rather than the square of the gain.  This PR fixes that bug.
=> Variances should be divided by gain**2, rather than gain.

romanisim/l1.py
This PR clips the number of photons entering a pixel over an exposure to 2 * 10**9 to avoid floating point / integer math issues.  This seems like a lot of photons, but a 0th mag star should generate O(10^11) photons per second per meter squared, so it's not _that_ many.  Roman saturates at O(10^5) photons and we really only need to care about handling enough to saturate in a single read; this lets us handle exposure times up to ~2*10^4 reads which seems like more than enough.  The non-linearity correction will have issues long before this and would be the next thing to look at if we wanted to do a better job with very bright stars.
=> Convert counts to integer to avoid floating point weirdness.

docs/romanisim/running.rst, scripts/romanisim-make-image
On main, users can generate images for all SCAs using `romanisim-make-image ... --sca -1 ...`, in a case that gets caught here:
https://github.com/spacetelescope/romanisim/blob/e0e6a979db8b43cbdb22e8082ae14e9ed2f8cd4d/scripts/romanisim-make-image#L27-L37
This feature isn't written about in the docs or in the argument's help notes, so I've added a note to both.
=> Document feature for generating images with all SCAs

romanisim/image.py, romanisim/l1.py, romanisim/parameters.py, romanisim/tests/test_l1.py, romanisim/tests/test_ramp.py, tox.ini
Adds correlated noise across all reads associated with noise in the reference read (frame zero), which is subtracted from all subsequent reads.
A new parameter, pedestal_extra_noise, is added, with a default value of 4 DN.  Noise is added to all resultants in each pixel with amplitude equal to the quadrature sum of the pixel's read noise and the extra pedestal noise.
This noise is degenerate with the pedestal and so doesn't meaningfully affect final ramp measurements at present.
We use a separate RNG so that pedestal noise can be turned on and off without affecting the rest of the random numbers in the simulation.
I also added corresponding tests.
=> Add frame zero effects.

pyproject.toml
resolves [SCSB-155](https://jira.stsci.edu/browse/SCSB-155)
Numpy 2.0 is scheduled for release on June 19th. Due to the C ABI updates, Python projects that build C extensions are required to build against Numpy 2.0 in order to use Numpy 2.0 in runtime.
This is backwards-compatible with Numpy versions in runtime as far back as `1.26`
this PR pins `numpy>=2.0.0rc2` in `build-system.requires`
> [!NOTE]
> this PR was generated automatically by ``batchpr`` :robot:
=> [SCSB-155] build with Numpy 2.0

docs/index.rst, docs/romanisim/image-input.rst, romanisim/catalog.py, romanisim/tests/test_image.py, romanisim/util.py
Add support for image input to the simulator.
Conceptually, the idea is that users may have a set of "truth" data as to what real galaxies look like.  This could come from hydro simulations or deep images of galaxies.  These galaxies have better fidelity than the kind of simple parametric galaxies ordinary catalog input supports.
This PR adds a new kind of catalog input mode, where the catalog input includes an 'ident' field that indicates which galaxy in a catalog of galaxy images should be input into an image at a given location.  On top of that, it includes additional fields that specify how that galaxy image should be sheared, dilated, or rotated.  The image is then rendered with the given galaxies at the given locations.
This feature leverages the RealGalaxyCatalog class in GalSim, …
=> Add support for image input

.github/workflows/build.yml
Resolves [SCSB-170](https://jira.stsci.edu/browse/SCSB-170)
=> [SCSB-170] pin Python<3.13

romanisim/image.py, romanisim/l1.py, romanisim/parameters.py, romanisim/ris_make_utils.py, romanisim/util.py, romanisim/wcs.py
This PR makes a number of metadata changes for science verification.  The pixels are not affected.  It is intended to address #136 .  
Some of the changes:
- There is now a "version" keyword in the 'romanisim' section of the output:
```
>>> asdf.open('l1.asdf')['romanisim']['version']
'0.5.3.dev9+g273099b'
```
- guide window metadata is set to size 16
```
>>> asdf.open('l1.asdf')['roman']['meta']['guidestar']['gw_window_xsize']
16
>>> asdf.open('l1.asdf')['roman']['meta']['guidestar']['gw_window_ysize']
16
```
- photometry metadata is now -999999 for L1 files but has sensible values for L2 files.
```
>>> asdf.open('l2.asdf')['roman']['meta']['photometry']
{'conversion_microjanskys': <Quantity 15.11015947 uJy / arcsec2>, 'conversion_megajanskys': <Quantity 0.64286431 MJy / sr>, …
```
=> Metadata updates for science verification.

.github/dependabot.yml, .github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/data.yml
This PR pins github actions to hashes (rather than versions) as recommended by github:
https://wellarchitected.github.com/library/application-security/scenarios-and-recommendations/actions-security/#pin-versions-of-actions
and enables dependabot to check these monthly. Dependabot will open PRs requesting updates when new versions of actions are released.
=> Add Dependabot to update github actions and pin actions to hash

romanisim/l3.py
Closes #173.  Larry identified an issue where we were overwriting the intended metadata with default metadata instead of the other way around; this PR changes the order of things to avoid that goof.
@larrybradley, I went ahead and updated the files on /grp/roman/eschlafly/romanisim/ in place to fix this.  The actual data also likely changed since I suspect that I was actually just simulating the same filter repeatedly; thank you!
=> Make sure user-specified metadata isn't blown away by default metadata.

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/data.yml, .github/workflows/retrieve_cache.yml
we're attempting to test `romanisim` as part of `gwcs`'s downstream testing, and it would be very useful to be able to use this workflow to set up the webbpsf + GALSIM data cache for there:
- https://github.com/spacetelescope/gwcs/pull/530
This involves adding the `workflow_call` trigger and also allowing the user to specify the download path for the data
=> allow data workflows (WebbPSF + GALSIM) to be used by upstream repos for downstream testing

romanisim/image.py
When more than 2 billion photons are modeled as entering a pixel, the current code trips and dies.  This caps the number of photons entering a pixel to 2**31 - 1.
=> Handle cases where more than 2 billion photons enter a pixel.

pyproject.toml
An attempted regtest run with python 3.13 showed a failure when the test machine failed to build `getch`:
https://github.com/spacetelescope/RegressionTests/actions/runs/12264011982/job/34217036983?pr=183#step:14:38
I don't see any uses of this package. (FWIW The python 3.13 tests aren't failing in the CI here so the above failure could be seen as a bug in the proposed regtest test machine changes).
This PR removes unused dependencies:
- getch: looks like a dead package (no release since 2013): https://pypi.org/project/getch/
- colorama: this isn't imported
- flake8: this was replaced by ruff
=> Drop unused dependencies

romanisim/image.py, romanisim/l3.py, romanisim/tests/test_l3.py, romanisim/tests/test_wcs.py, romanisim/util.py, romanisim/wcs.py
romanisim was using the wcs.pixel_to_world and world_to_pixel routines when it should have been using the _values versions of those routines.  These routines have become more strict about their inputs; this updates the code to use the _values versions.
=> Update wcs interface to use pixel_to_world_values instead of non-values versions.

romanisim/image.py, romanisim/tests/test_image.py
This fixes #193 using the solution described in that issue.
I've also added a test for the case causing the error -- even though the error only occurs on some architectures, there's always a warning from numpy about the potential overflow, so the test checks for that.
=> Fix floating point issues

.github/workflows/data.yml, .github/workflows/download_data.yml
Similar to https://github.com/spacetelescope/romancal/pull/1619
This won't work until:
- it's merged
- the cache is regenerated (by running https://github.com/spacetelescope/romanisim/actions/workflows/data.yml)
This is a stop-gap fix until this package can be migrated to stpsf.
=> fix webbpsf data download cache

romanisim/parameters.py, romanisim/ris_make_utils.py, romanisim/tests/test_ris_make_utils.py, scripts/romancal_make_all_l1s.sh, scripts/romancal_make_regtest_l1s.sh, scripts/romanisim-make-catalog, scripts/romanisim-make-image, scripts/romanisim-make-stack
The Roman L1 & L2 file naming scheme was changed to include the filter name in lowercase in the file name.  This PR implements that change in the romanisim regtest file creation routines.  It also tries to make a more general routine for "automatically" getting the bandpass in the filename, supporting filename arguments like
romanisim-make-image out-{}-{bandpass}.asdf
to produce out-wfi01-f087.asdf.  The naming for the SCA argument should have been {sca} in retrospect, but we retain the old API that was used to support
romanisim-make-image out-{}.asdf --sca -1
to trigger generating all 18 SCAs with names like out-wfi01.asdf.
This PR also adds back MA tables 109 and 110.  These are not officially supported as part of the PRD, so they were removed.  But they have spectroscopic & imaging …
=> Updates for putting filters in filenames in romanisim.

romanisim/tests/test_catalog.py
The setup for this test assumes that the tests are being run from the romanism repo directory, this is not always the case such as when one is constructing test environments for testing romanism with an upstream package
=> Bugfix for upstream

pyproject.toml, romanisim/catalog.py
I didn't quite fix all the issues with #212, there were some remaining ones. The issue is that the code was implicitly assuming that the default data file for generating a catalog was with stored respect the layout one gets when one clones the repository with the code run from the root of the repository. This does not hold in general as one can run the code outside that layout. The fix is to reference the data file with respect to the module making the call rather than the directory the code is executing in.
Also, I enabled colorized output in the tests by default because its pretty.
=> More bug fixes for upstream testing

romanisim/l1.py, romanisim/wcs.py
The migration away from maker_utils ended up having (at least) two unintended consequences:
- amp33 was getting populated as a [n_resultants, 4096, 4096] array instead of the usual [n_resultants, 4096, 128] array.  This inflates the size of the L1 files and leads to breakage in the reference pixel correction step.  We didn't notice this since romanisim itself doesn't actually do anything with amp33.
- mk_level2_image was making a data array with a 4k x 4k shape, but create_fake_data was leaving this 0x0 by default.  The WCS creation was using the size in setting the bounding box, which was leading to a 0x0 bounding box in some cases.
This PR fixes those two issues.
=> Fix amp33 and wcs to allow pipeline processing

romanisim/l3.py, romanisim/tests/test_l3.py, romanisim/util.py
This PR makes a few fixes to romanisim-make-l3 to make sure it makes valid L3 files:
- Fix ra/dec corner metadata.
- Make merge_dicts handle more dict-like objects.
- Force variances to f4.
- Return a node rather than a model from l3.simulate.
- Add an L3 asdf validation test.
=> Make sure romanisim-make-l3 makes valid L3 files.

romanisim/l3.py
Hi, I attempted to rectify what seems like an unintentional difference between simulating L2 and L3 images. 
Although both use `galsim.roman.GetSkyLevel()`, L2's implementation in `romanisim/image.py` provides a date while L3's doesn't. If a date isn't specified, `GetSkyLevel()` assumes the Sun is at coordinates (0, 0) and throws an error saying the catalog is too close to the Sun for an observation to take place. I just happened to try to simulate with a catalog centered there during science validation.
It also seems like `galsim.ImageF()` prefers taking the image as a pure numpy array instead of `image.data`'s initial `asdf.tags.core.ndarray.NDArrayType` type.
=> Allow L3 sims near (0,0)

romanisim/ris_make_utils.py
We now use product_type = WFI_SPECTRAL instead of WFI_PRISM / WFI_GRISM; romanisim should populate these correctly.
=> Change WFI_{GRISM/PRISM} -> WFI_SPECTRAL product type

pyproject.toml, romanisim/catalog.py, romanisim/gaia.py
The old flux units of GAIA and COSMOS tables were being preserved in RSIM catalog output - this PR removes them. It also fixes a couple comments that referred to the output flux being in Janskys, when they are in maggies.
=> Correct Units in Output Catalog and Comments
