docs/conf.py
Add intersphinx configuration directives to pull in docs from other sites and remove warnings.
=> Intersphinx

docs/conf.py, docs/index.rst, docs/romanisim/image.rst, docs/romanisim/install.rst, docs/romanisim/l2.rst, docs/romanisim/overview.rst, romanisim/__init__.py, romanisim/catalog.py, romanisim/image.py, romanisim/l1.py, romanisim/psf.py, romanisim/ramp.py, romanisim/util.py, scripts/romanisim-make-image, setup.py
This PR adds ramp fitting routines and constructs L2 images from L1 images using them.  It also adds the corresponding docs.
=> Construct L2 images from L1 images via ramp fitting.

.github/workflows/ci.yml, requirements-dev.txt, romanisim/wcs.py, tox.ini
copying new PR from `romancal` (https://github.com/spacetelescope/romancal/pull/551)
=> refactor `tox` environment factors

romanisim/catalog.py, romanisim/tests/test_catalog.py
Add tests on the various catalog routines.
=> Add some tests of the catalog modules.

romanisim/l1.py, romanisim/ramp.py, romanisim/tests/test_ramp.py
Add tests of ramp fitting routines.
Fix minor issues in l1 and ramp routines that don't broadcast well that came up when adding ramp fitting tests.
=> Add ramp fitting tests.

README.md, romanisim/psf.py, scripts/romanisim-make-image
Add an admonition so that people are aware of the current state of romanisim's development.
=> Admonition

romanisim/tests/test_wcs.py, romanisim/wcs.py
Clean up some long lines in the WCS module.
Refactor the WCS module slightly to allow passing in a distortion model instead of grabbing one from WCS to ease testing.
=> Add unit tests for WCS module.

romanisim/catalog.py, romanisim/image.py, romanisim/psf.py, romanisim/tests/test_image.py, romanisim/tests/test_util.py, romanisim/util.py
This PR fills out a bit more of the simulation metadata to make it easier for users to find things.
It also fixes one bug where Poisson noise was being applied twice.
=> Add more metadata to the simulation output headers.

docs/romanisim/l1.rst, romanisim/cr.py, romanisim/image.py, romanisim/l1.py, romanisim/tests/test_cr.py, romanisim/tests/test_image.py
This PR adds @jwuphysics 's CR module to the simulator, adding CRs as reads are simulated in the L1 module.
=> Add CRs to simulator

docs/index.rst, docs/romanisim/l1.rst, docs/romanisim/overview.rst, docs/romanisim/running.rst, pyproject.toml, romanisim/image.py, romanisim/l1.py, romanisim/parameters.py, romanisim/persistence.py, romanisim/tests/test_image.py, romanisim/tests/test_persistence.py, scripts/romanisim-make-image
This PR adds persistence to the simulator following the Fermi prescription used in Galsim and in Sanchez+2023.
=> Add persistence to simulator

.github/workflows/ci_cron.yml, tox.ini
=> remote `--upgrade-strategy eager` to relax environment resolution

romanisim/catalog.py, romanisim/parameters.py, scripts/ris_make_utils.py, scripts/romanisim-make-image, scripts/romanisim-make-stack
Creation of a script to make multiple images based on CSV input. The script is to either actually make the simulated files or output a text files with appropriate command lines required to create the files (good for computer clusters).
=> RCAL-576 Initial Apt Support

JenkinsfileRT_dev
This updates the Jenkis file to point to the new WebbPSF data directory.
=> Update webbpsf data location in Jenkins.

.readthedocs.yaml, docs/romanisim/l1.rst, romanisim/tests/test_catalog.py, romanisim/tests/test_image.py, romanisim/tests/test_l1.py
This PR adds some asdf binary files with the various images & test statistics computed during the B11 tests.
=> Add test artifacts to B11 tests.

romanisim/catalog.py, romanisim/cr.py, romanisim/image.py, romanisim/l1.py, romanisim/parameters.py, romanisim/persistence.py, romanisim/ris_make_utils.py, romanisim/tests/test_cr.py, romanisim/tests/test_image.py, romanisim/tests/test_l1.py, romanisim/tests/test_linear.py, romanisim/tests/test_util.py, romanisim/tests/test_wcs.py, romanisim/util.py, romanisim/wcs.py, scripts/romanisim-make-image, scripts/romanisim-make-stack
Adding support for an input configuration file that would override romanisim.parameters and allow for changing parameters like metadata, general default constants, and API options.
=> RCAL-580 Input Config File

romanisim/l1.py, romanisim/util.py
This PR adds the read_pattern to simulated images.
Fixes https://github.com/spacetelescope/romanisim/issues/88.
=> Add read_pattern metadata to simulated files.

romanisim/bandpass.py, romanisim/tests/test_bandpass.py
Updated photometry code to support an input spectra. Added a sanity AB Zero test as well as DMS 233 test.
=> RCAL-748 Synthetic Photometry

romanisim/image.py, romanisim/ris_make_utils.py, romanisim/tests/test_ris_make_utils.py
This PR sets additional meta.observation metadata from the file name when a Roman L2-like filename is detected.
=> Add metadata from filename.

.github/workflows/build.yml, pyproject.toml, setup.py
Resolves [SCSB-149](https://jira.stsci.edu/browse/SCSB-149)
=> ensure extension modules are present in built wheel

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/data.yml
attempt to make WebbPSF data download / caching step simpler and more maintainable
=> abstract data download step into separate reusable workflow

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/data.yml, .github/workflows/retrieve_cache.yml
centralize WebbPSF data caching to the reusable workflow in `spacetelescope/webbpsf`
=> use reusable workflow from WebbPSF repository to download and cache data

.github/workflows/build.yml, pyproject.toml
Resolves [SCSB-170](https://jira.stsci.edu/browse/SCSB-170)
follow-on to #139
=> [SCSB-170] pin Python<3.13 (take 2)

romanisim/tests/test_l1.py
I had omitted to include DMS223 in the metrics logger decorator.  This PR adds that missing decoration.
=> Update decorator to include DMS223

romanisim/__init__.py
This PR increases the log level to make sure we get all the log messages we want output from the tests.
=> Increase log verbosity.

scripts/romanisim-make-image
This updates the default MA table to change away from the now-removed MA table 1.  Resolves #189 .
=> Update default MA table number in romanisim-make-image.

.github/workflows/ci.yml, .github/workflows/ci_cron.yml
[SCSB-195](https://jira.stsci.edu/browse/SCSB-195)
=> test with latest supported Python version

docs/romanisim/running.rst, pyproject.toml, romanisim/image.py, romanisim/ris_make_utils.py, scripts/romanisim-make-image
The following hooks just allow passing in an additional array to be added to the simulation. This now just needs to get added  into the main script.
=> Ability to add in extra_counts
